96boards-hikey-aosp-master: install qa-reports dependency
Change-Id: I6e8d21db462eca96bc66747e8d9262cd8dac05ca
Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>

diff --git a/96boards-hikey-aosp-master.yaml b/96boards-hikey-aosp-master.yaml
--- a/96boards-hikey-aosp-master.yaml
+++ b/96boards-hikey-aosp-master.yaml
@@ -59,6 +59,21 @@
               http://mirrors.kernel.org/ubuntu/pool/universe/o/openjdk-8/openjdk-8-jdk_8u45-b14-1_amd64.deb
             sudo dpkg -i --force-all *.deb
 
+            if ! sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 update; then
+              echo "INFO: apt update error - try again in a moment"
+              sleep 15
+              sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 update || true
+            fi
+            pkg_list="python-pip"
+            if ! sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 install -y ${pkg_list}; then
+              echo "INFO: apt install error - try again in a moment"
+              sleep 15
+              sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 install -y ${pkg_list}
+            fi
+
+            # Install ruamel.yaml
+            pip install --user --force-reinstall ruamel.yaml
+
             mkdir -p ${HOME}/bin ${WORKSPACE}/build/out
             curl https://storage.googleapis.com/git-repo-downloads/repo > ${HOME}/bin/repo
             chmod a+x ${HOME}/bin/*
