ledge: add lava job for debian
The lava job launch qemu test for the two architectures:
armhf and arm64.

Change-Id: Ied326e17976c59fbf9cabc77ed330bfce6c0c0b0
Signed-off-by: Christophe Priouzeau <christophe.priouzeau@linaro.org>

diff --git a/ledge-armhf-debian.yaml b/ledge-armhf-debian.yaml
--- a/ledge-armhf-debian.yaml
+++ b/ledge-armhf-debian.yaml
@@ -50,6 +50,40 @@
     builders:
         - shell:
             !include-raw: ledge-debian/builders-fai.sh
+        - shell: |
+            #!/bin/bash
+            cat << EOF > ${WORKSPACE}/post_build_lava_parameters
+            DEPLOY_DIR_IMAGE=`pwd`/out
+            BASE_URL=https://snapshots.linaro.org
+            BOOT_URL=
+            ROOTFS_SPARSE_BUILD_URL=
+            KERNEL_URL=https://snapshots.linaro.org/${PUB_DEST}/Image-for-debian
+            DTB_URL=
+            RECOVERY_IMAGE_URL=
+            SYSTEM_URL=https://snapshots.linaro.org/${PUB_DEST}/FlashLayout_sdcard_armhf_without_boot_firmware.raw
+            NFSROOTFS_URL=https://snapshots.linaro.org/${PUB_DEST}/rootfs-linaro-buster-*-unknown-*.tar.xz
+            EXT4_IMAGE_URL=
+            HDD_URL=
+            KERNEL_COMMIT=
+            KERNEL_CONFIG_URL=
+            KERNEL_DEFCONFIG_URL=
+            KSELFTESTS_MAINLINE_URL=
+            KSELFTESTS_MAINLINE_VERSION=
+            KSELFTESTS_NEXT_URL=
+            KSELFTESTS_NEXT_VERSION=
+            LTP_URL=
+            LTP_VERSION=
+            LTP_REVISION=
+            LIBHUGETLBFS_URL=
+            LIBHUGETLBFS_VERSION=
+            LIBHUGETLBFS_REVISION=
+            MAKE_KERNELVERSION=
+            TOOLCHAIN=
+            KERNEL_ARGS=${KERNEL_ARGS}
+            INITRD_URL=
+            EOF
+        - inject:
+            properties-file: post_build_lava_parameters
         - linaro-publish-token
         - shell: |
             # Publish to snapshots
@@ -59,6 +93,56 @@
                  --server ${PUBLISH_SERVER} \
                  --link-latest \
                  out ${PUB_DEST}
+        - shell: |
+            #!/bin/bash
+
+            if ! sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 update; then
+                 echo "INFO: apt update error - try again in a moment"
+                 sleep 15
+                 sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 update || true
+            fi
+
+            pkg_list="chrpath cpio diffstat gawk git expect pkg-config python-pip python-requests python-crypto libpixman-1-dev python python3 python-all-dev python-wheel"
+            if ! sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 install -y ${pkg_list}; then
+                 echo "INFO: apt install error - try again in a moment"
+                 sleep 15
+                 sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 install -y ${pkg_list}
+            fi
+
+            sudo locale-gen en_US.UTF-8 && sudo update-locale LANG=en_US.UTF-8
+            export LC_ALL=en_US.UTF-8
+
+            # install required python modules
+            pip install --user --force-reinstall Jinja2 ruamel.yaml
+
+            rm -rf configs
+            git clone --depth 1 http://git.linaro.org/ci/job/configs.git
+            sed -i 's/job_name: RPB OE/job_name: RPB Debian ARM64/' configs/rpb-openembedded/lava-job-definitions/*/template-boot.yaml
+
+            #export takes more priority then argument provided with --device-type
+            export DEVICE_TYPE=qemuarmuefi
+            export MACHINE="ledge-qemuarm"
+
+            [ -z "${MANIFEST_COMMIT}" ] && export MANIFEST_COMMIT="HEAD"
+            [ -z "${MANIFEST_BRANCH}" ] && export MANIFEST_BRANCH="master"
+            [ -z "${KSELFTEST_PATH}" ] && export KSELFTEST_PATH="/opt/kselftests/mainline/"
+            [ -z "${LAVA_JOB_PRIORITY}" ] && export LAVA_JOB_PRIORITY="25"
+            [ -z "${SANITY_LAVA_JOB_PRIORITY}" ] && export SANITY_LAVA_JOB_PRIORITY="30"
+            [ -z "${QA_SERVER_TEAM}" ] && export QA_SERVER_TEAM=rpb
+            [ -z "${TOOLCHAIN}" ] && export TOOLCHAIN="unknown"
+            [ -z "${TDEFINITIONS_REVISION}" ] && export TDEFINITIONS_REVISION="kselftest-5.1"
+
+            python configs/openembedded-lkft/submit_for_testing.py \
+                 --device-type ${DEVICE_TYPE} \
+                 --build-number ${BUILD_NUMBER} \
+                 --lava-server ${LAVA_SERVER} \
+                 --qa-server ${QA_SERVER} \
+                 --qa-server-team ${QA_SERVER_TEAM} \
+                 --qa-server-project ${QA_SERVER_PROJECT} \
+                 --git-commit ${MANIFEST_COMMIT} \
+                 --template-path configs/rpb-openembedded/lava-job-definitions \
+                 --template-names template-boot.yaml
+
     publishers:
         - groovy-postbuild:
             script:
