robher-aosp: print make return code
Signed-off-by: Rob Herring <robh@kernel.org>

diff --git a/robher-aosp.yaml b/robher-aosp.yaml
--- a/robher-aosp.yaml
+++ b/robher-aosp.yaml
@@ -97,8 +97,9 @@
             done
 
             ###### Don't care about artifacts for now ######
-            echo "Build for mesa rev ${rev} finished."
-            exit $failed
+            echo "Build for mesa rev ${rev} finished - ret ${failed}"
+            exit ${failed}
+
     publishers:
         - logparser:
             parse-rules: '/var/lib/jenkins/userContent/android.parse'
