tcwg-llvm-testsuite-diana: Use v2 interface
Replace BUILD_CONTAINER stuff with <prefix>_CONTAINER_RSH, as suggested
by Maxim in
https://review.linaro.org/#/c/20757/1/tcwg-llvm-testsuite.yaml

I'm not sure why this affects how parameters are passed, but it's worth
giving it a try to see how it behaves.

Change-Id: I8111a3647eeff0e2fc4a37c135ad5a9a1da59b0a

diff --git a/tcwg-llvm-testsuite-diana.yaml b/tcwg-llvm-testsuite-diana.yaml
--- a/tcwg-llvm-testsuite-diana.yaml
+++ b/tcwg-llvm-testsuite-diana.yaml
@@ -104,22 +104,15 @@
 
             # Start build container
             builder=$(print_host_for_node $NODE_NAME)
-            bash ${WORKSPACE}/start-container-docker.sh --arch ${builder_arch} --distro ${build_container_tag} --session-host ${builder} > build-container.sh
+            bash ${WORKSPACE}/start-container-docker.sh --arch ${builder_arch} --distro ${build_container_tag} --session-host ${builder} --prefix build_ > build-container.sh
 
-            # Define CONTAINER, CONTAINER_CLEANUP, session_host and session_port
+            # Define build_CONTAINER_RSH and build_container_cleanup
             . ./build-container.sh
-            BUILD_CONTAINER="${CONTAINER}"
-            BUILD_CONTAINER_CLEANUP="${CONTAINER_CLEANUP}"
 
-            # Make sure to cleanup build container if something goes
-            # wrong when preparing the test environment
-            if [ "${BUILD_CONTAINER_CLEANUP:+set}" = "set" ]; then
-                CONTAINERS_CLEANUP="${BUILD_CONTAINER_CLEANUP}"
-                trap "${CONTAINERS_CLEANUP}" EXIT
-            fi
+            trap "build_container_cleanup" EXIT
 
             # Setup job parameters and run
-            ${BUILD_CONTAINER} "cd ${WORKSPACE} && bash -x ${WORKSPACE}/tcwg-llvm-testsuite.sh \
+            ${build_CONTAINER_RSH} "cd ${WORKSPACE} && bash -x ${WORKSPACE}/tcwg-llvm-testsuite.sh \
                                       --workspace=${WORKSPACE} \
                                       --toolchain=${toolchain} \
                                       --nt-flags=${nt_flags}"
