tcwg-buildfarm-maxim: Robustify log compression
Change-Id: I38442b7222fd26f29801e1a3ff74a11db2a7fe40

diff --git a/tcwg-buildfarm-maxim.yaml b/tcwg-buildfarm-maxim.yaml
--- a/tcwg-buildfarm-maxim.yaml
+++ b/tcwg-buildfarm-maxim.yaml
@@ -267,9 +267,9 @@
 
                   # Save logs and their directory structure
                   rsync -a --exclude="/logs/" --include="*/" --include="*.log" --include="*.err" --include="*.out" --include="*.txt" --exclude="*" --prune-empty-dirs ./ ./logs/
-                  if which pxz; then
-                    tar -I pxz -cf ./artifacts/logs.tar.xz ./logs/
-                  else
+                  if ! tar -I pxz -cf ./artifacts/logs.tar.xz ./logs/; then
+                    # PXZ can [rarely] fail due to high RAM usage, so fallback to normal XZ.
+                    rm -f ./artifacts/logs.tar.xz
                     tar -cJf ./artifacts/logs.tar.xz ./logs/
                   fi
 
