tcwg_kernel: Re-indent code for easier comparison with tcwg_bmk version
Change-Id: I68a71d0b6670d0687e89eae15d825a5752a69c09

diff --git a/tcwg_kernel.yaml.in b/tcwg_kernel.yaml.in
--- a/tcwg_kernel.yaml.in
+++ b/tcwg_kernel.yaml.in
@@ -99,8 +99,7 @@
           name: gcc_branch
           default: default
           description: "gcc branch or sha1 to build"
-#endif
-#if TOOLCHAIN_llvm
+#elif TOOLCHAIN_llvm
       - string:
           name: llvm_branch
           default: default
@@ -152,64 +151,63 @@
           users:
             - 'e0958a95-204f-4c14-a66c-5e2be6c5d50a'
     builders:
-        - shell:
-            command: |
-                #!/bin/bash
-                set -ex
-                # Delete artifacts now to avoid re-using stale artifacts if
-                # below docker-run.sh fails to start up a container.
-                rm -rf artifacts/
-                mkdir -p artifacts/jenkins
-                build_name="#$BUILD_NUMBER"
-                branch_opt=""
-                # 1 to skip jenkins-scripts
-                i=1
-                for c in {components}; do
-                  eval "b=\$$$${{c}}_branch"
-                  if [ x"$b" = x"default" ]; then
-                    eval "b=\$GIT_COMMIT_$i"
-                  fi
-                  if [ x"$b" != x"baseline" ]; then
-                    build_name="$build_name-$c"
-                    branch_opt="$branch_opt ==rr[${{c}}_branch] $b"
-                  fi
-                  i=$(($i+1))
-                done
+      - shell:
+          command: |
+            #!/bin/bash
+            set -ex
+            # Delete artifacts now to avoid re-using stale artifacts if
+            # below docker-run.sh fails to start up a container.
+            rm -rf artifacts/
+            mkdir -p artifacts/jenkins
+            build_name="#$BUILD_NUMBER"
+            branch_opt=""
+            # 1 to skip jenkins-scripts
+            i=1
+            for c in {components}; do
+              eval "b=\$$$${{c}}_branch"
+              if [ x"$b" = x"default" ]; then
+                eval "b=\$GIT_COMMIT_$i"
+              fi
+              if [ x"$b" != x"baseline" ]; then
+                build_name="$build_name-$c"
+                branch_opt="$branch_opt ==rr[${{c}}_branch] $b"
+              fi
+              i=$(($i+1))
+            done
 
-                ./jenkins-scripts/docker-run.sh \
-                --distro $distro \
-                -- \
-                ./jenkins-scripts/tcwg_kernel-build.sh \
-                %% artifacts/jenkins/manifest.sh \
-                --BUILD_URL "$BUILD_URL" \
-                ==rr[ci_config] {toolchain_name}-{toolchain_ver}-{target}-{linux}-{linux_config} \
+            ./jenkins-scripts/docker-run.sh \
+            --distro $distro \
+            -- \
+            ./jenkins-scripts/tcwg_kernel-build.sh \
+            %% artifacts/jenkins/manifest.sh \
+            --BUILD_URL "$BUILD_URL" \
+            ==rr[ci_config] {toolchain_name}-{toolchain_ver}-{target}-{linux}-{linux_config} \
 #if TOOLCHAIN_gnu
-                ==rr[binutils_url] {binutils_url} \
-                ==rr[gcc_url] {gcc_url} \
+            ==rr[binutils_url] {binutils_url} \
+            ==rr[gcc_url] {gcc_url} \
+#elif TOOLCHAIN_llvm
+            ==rr[llvm_url] {llvm_url} \
 #endif
-#if TOOLCHAIN_llvm
-                ==rr[llvm_url] {llvm_url} \
-#endif
-                ==rr[linux_url] {linux_url} \
-                $branch_opt \
-                ==rr[mode] "jenkins-full" \
-                ==rr[update_baseline] "$update_baseline" &
-                res=0 && wait $! || res=$?
+            ==rr[linux_url] {linux_url} \
+            $branch_opt \
+            ==rr[mode] "jenkins-full" \
+            ==rr[update_baseline] "$update_baseline" &
+            res=0 && wait $! || res=$?
 
-                if [ $res != 0 ]; then
-                  touch artifacts/failures
-                fi
+            if [ $res != 0 ]; then
+              touch artifacts/failures
+            fi
 
-                if [ -e artifacts/results ]; then
-                  build_name="$build_name-R$(tail -n1 artifacts/results)"
-                fi
-                if [ x"$update_baseline" != x"update" ]; then
-                  build_name="$build_name-$update_baseline"
-                fi
-                if [ -f artifacts/trigger-bisect ]; then
-                  build_name="$build_name-bisect"
-                fi
-                echo "$build_name" > artifacts/jenkins/build-name
+            if [ -e artifacts/results ]; then
+              build_name="$build_name-R$(tail -n1 artifacts/results)"
+            fi
+            if [ x"$update_baseline" != x"update" ]; then
+              build_name="$build_name-$update_baseline"
+            fi
+            if [ -f artifacts/trigger-bisect ]; then
+              build_name="$build_name-bisect"
+            fi
+            echo "$build_name" > artifacts/jenkins/build-name
         - trigger-followup-builds:
             ci_config: '{toolchain_name}-{toolchain_ver}-{target}-{linux}-{linux_config}'
         - shell: |
@@ -301,8 +299,7 @@
 #if TOOLCHAIN_gnu
             ==rr[binutils_url] {binutils_url} \
             ==rr[gcc_url] {gcc_url} \
-#endif
-#if TOOLCHAIN_llvm
+#elif TOOLCHAIN_llvm
             ==rr[llvm_url] {llvm_url} \
 #endif
             ==rr[linux_url] {linux_url}
