tcwg_gnu.yaml: Conditionally run post build steps.
This allows us to propogate UNSTABLE result
when we skip a bad config.

The docker-run stage will always be a SUCCESS
even if the command fails, we exit properly
in the post build step. Setting FAILURE state.

Change-Id: I79ae03a50942392497ef204acff30c36d26cd688

diff --git a/tcwg_gnu.yaml b/tcwg_gnu.yaml
--- a/tcwg_gnu.yaml
+++ b/tcwg_gnu.yaml
@@ -273,13 +273,19 @@
                 fi
                 echo "$build_name" > artifacts/jenkins/build-name
             unstable-return: 100
-        - trigger-followup-builds:
-            ci_config: '{toolchain_name}-{toolchain_ver}-{target}-{type_of_test}'
-        - shell: |
-            #!/bin/bash
-            if [ -f artifacts/failures ]; then
-              exit 1
-            fi
+        - conditional-step:
+            # Only run if above succeeded
+            # Meaning we did not skip a bad config
+            # (a failed build is indicated by artifacts/failures)
+            condition-kind: current-status
+            steps:
+              - trigger-followup-builds:
+                  ci_config: '{toolchain_name}-{toolchain_ver}-{target}-{type_of_test}'
+              - shell: |
+                  #!/bin/bash
+                  if [ -f artifacts/failures ]; then
+                    exit 1
+                  fi
     publishers:
         - archive:
             artifacts: 'artifacts/**'
