tcwg-buildfarm-bernie: Update after review
Multiple changes:
s/Backbench/Buildbench: We are kicking off a benchmark
on every build, not on every backport. Name accordingly.

Add comment to inject step.

Check for overmatching of artifact patterns.

Don't try to dispatch a benchmark unless Jenkins succeeded.

Change-Id: Id73b2d32c7847ee6283e2d19e1e1d168f8fde858

diff --git a/tcwg-buildfarm-bernie.yaml b/tcwg-buildfarm-bernie.yaml
--- a/tcwg-buildfarm-bernie.yaml
+++ b/tcwg-buildfarm-bernie.yaml
@@ -185,51 +185,58 @@
 
             result="0"
             ${BUILD_SHELL} -x ./jenkins.sh --target ${target} --gcc-branch ${gcc_branch} --languages ${languages} $bootstrap $runtests_opt $excludecheck_opt --fileserver ex40-01.tcwglab.linaro.org/snapshots-ref --logserver $log_server $logname_opt $norebuild -o '--tarbin' || result=$?
+            echo "Result of jenkins.sh: $result"
 
-            #Do not trigger a benchmark if jenkins.sh exits without error and
-            #without having built a toolchain (probably because --norebuild was
-            #set and the logs already existed).
             #trigger-builds will only trigger if the properties file exists, so
             #create the file conditionally
-            if test -e snapshots/gcc-linaro-*.tar.xz; then
+            if test ${result} -eq 0; then
               #Cases for which we want to trigger a benchmark
               if test "x${target}" = xarm-linux-gnueabihf ||
                  test "x${target}" = xaarch64-linux-gnu; then
+                #Only trigger if jenkins.sh exits without error _and_ the
+                #artifacts exist. (If --norebuild is set and logs already
+                #exist, there will be no error but also no artifacts.)
                 toolchain="`ls snapshots/gcc-linaro-*.tar.xz`"
                 sysroot="`ls snapshots/sysroot-*-linaro-*.tar.xz`"
-                cat > bench_parameters <<EOF
-            BENCHMARK=Coremark-Pro
-            TOOLCHAIN=${JENKINS_URL}/job/${JOB_NAME}/${BUILD_NUMBER}/artifact/${toolchain}
-            SYSROOT=${JENKINS_URL}/job/${JOB_NAME}/${BUILD_NUMBER}/artifact/${sysroot}
-            TARGET_CONFIG=Juno-A57
-            RUN_FLAGS=quickrun
-            Overrides=BUNDLE_STREAM=/anonymous/backbench/
-            LAVA_JOB_NAME=Backbench: ${target} Coremark-Pro on Juno-A57
+                if test `echo ${toolchain} | wc -l` -eq 1 &&
+                   test `echo ${sysroot}   | wc -l` -eq 1; then
+                  cat > bench_parameters <<EOF
+              BENCHMARK=Coremark-Pro
+              TOOLCHAIN=${JENKINS_URL}/job/${JOB_NAME}/${BUILD_NUMBER}/artifact/${toolchain}
+              SYSROOT=${JENKINS_URL}/job/${JOB_NAME}/${BUILD_NUMBER}/artifact/${sysroot}
+              TARGET_CONFIG=Juno-A57
+              RUN_FLAGS=quickrun
+              Overrides=BUNDLE_STREAM=/anonymous/backbench/
+              LAVA_JOB_NAME=Buildbench: ${target} Coremark-Pro on Juno-A57
             EOF
 
-                #Archives end up on public internet, so deliver source/scripts
-                #alongside prebuilt binaries
-                git archive HEAD -o source.tar
-                tar rf source.tar --exclude-vcs --exclude=${toolchain} --exclude=${sysroot} snapshots
-                xz source.tar
+                  #Archives end up on public internet, so deliver source/scripts
+                  #alongside prebuilt binaries
+                  git archive HEAD -o source.tar
+                  tar rf source.tar --exclude-vcs --exclude=${toolchain} --exclude=${sysroot} snapshots
+                  xz source.tar
 
-                cat > artifact_parameters << EOF
+                  cat > artifact_parameters << EOF
             TOOLCHAIN=${toolchain}
             SYSROOT=${sysroot}
             EOF
-                #No need for a 'remove bench/artifact_params' case, as we wipe workspace
+                elif test `echo ${toolchain} | wc -l` -ne 0 ||
+                     test `echo ${sysroot}   | wc -l` -ne 0; then
+                  echo "Multiple matches for toolchain and/or sysroot tarball, cannot dispatch benchmark" >&2
+                  result=2
+                fi
+              #else... No need for a 'remove bench/artifact_params' case, as we wipe workspace
               fi
             fi
             touch artifact_parameters #This file must exist, as it is used in
                                       #an inject step, and inject won't fail
                                       #good if there is no file
 
-            echo "Result of jenkins.sh: $result"
             if $dont_fail; then
               result="0"
             fi
             exit $result
-        - inject:
+        - inject: #Create env vars used by achive step, below.
             properties-file: 'artifact_parameters'
 
         #If bench_parameters is missing, we don't set any parameters and
