tcwg-container-christophe: Use $host_arch instead of uname -m
Since the Jenkins script is now executed by the main slave,
not by a (docker) container inside it.
Thus, use i386 instead of i686...

Change-Id: Ie044d0282164de5b54a97a23043c752b733fbc01

diff --git a/tcwg-container-christophe.yaml b/tcwg-container-christophe.yaml
--- a/tcwg-container-christophe.yaml
+++ b/tcwg-container-christophe.yaml
@@ -52,7 +52,7 @@
             description: 'Rebuild the toolchain even if results are already on logserver'
         - string:
             name: log_name
-            default: '${JOB_NAME}-${BUILD_NUMBER}/$(uname -m).$target'
+            default: '${JOB_NAME}-${BUILD_NUMBER}/$(host_arch).$target'
             description: 'Logname directory on logserver'
         - bool:
             name: dont_fail
@@ -127,6 +127,7 @@
 
             git clone -b $scripts_branch --depth 1 https://git-us.linaro.org/toolchain/jenkins-scripts
 
+            # FIXME: Avoid recomputing this, we did it already in the previous script
             case ${label} in
                 tcwg-x86_64-cam) host_arch=amd64 ;;
                 tcwg-x86_32-build) host_arch=i386 ;;
@@ -193,13 +194,22 @@
                   # Define session_host and session_port, install trap
                   . ./container.sh
 
+                  case ${label} in
+                      tcwg-x86_64-cam) host_arch=amd64 ;;
+                      tcwg-x86_32-build) host_arch=i386 ;;
+                      tcwg-tx1-build) host_arch=arm64 ;;
+                      tcwg-tx1_32-build) host_arch=armhf ;;
+                      tcwg-tk1_32-build) host_arch=armhf ;;
+                      *) echo "ERROR: Unsupported slave: $slave"; exit 1 ;;
+                  esac
+
                   ${CONTAINER} 'echo "Build session is up; ulimit config:"; ulimit -a'
 
                   if [ -f test-container.param ]; then
                     runtests_opt="--runtests --testcontainerfile $WORKSPACE/test-container.data"
                   else
-                    case "$target_kind-$runtests-$(uname -m)" in
-                      *-"yes"-*|*-"x86_64-host"-"x86_64"|*-"x86_64-host"-"i686")
+                    case "$target_kind-$runtests-$(host_arch)" in
+                      *-"yes"-*|*-"x86_64-host"-"x86_64"|*-"x86_64-host"-"i386")
                         runtests_opt="--runtests"
                       ;;
                       *)
@@ -208,8 +218,8 @@
                     esac
                   fi
 
-                  case $(uname -m) in
-                    x86_64|i686) languages="$host_x86_64_languages" ;;
+                  case $(host_arch) in
+                    x86_64|i386) languages="$host_x86_64_languages" ;;
                     *) languages="$host_aarchXX_languages" ;;
                   esac
 
@@ -229,8 +239,8 @@
                     norebuild="--norebuild"
                   fi
 
-                  case $(uname -m) in
-                    x86_64|i686) excludecheck="$host_x86_64_excludecheck" ;;
+                  case $(host_arch) in
+                    x86_64|i386) excludecheck="$host_x86_64_excludecheck" ;;
                     *) excludecheck="$host_aarchXX_excludecheck" ;;
                   esac
 
