tcwg-binutils-docker: Do not use ssh-agent.
Update to match recent changes in start-container-docker.sh

Change-Id: I1595dde25ee0cc821b2b07ac46b1fcdc6de86cb4

diff --git a/tcwg-binutils-docker.yaml b/tcwg-binutils-docker.yaml
--- a/tcwg-binutils-docker.yaml
+++ b/tcwg-binutils-docker.yaml
@@ -77,10 +77,6 @@
         - timeout:
             timeout: 600
         - timestamps
-        - ssh-agent-credentials:
-            # tcwg-buildslave user id
-            users:
-                - 'e0958a95-204f-4c14-a66c-5e2be6c5d50a'
         - build-name:
             name: '#${BUILD_NUMBER}-${ENV,var="binutils_rev"}'
     builders:
@@ -105,8 +101,19 @@
 
             # Define CONTAINER, CONTAINER_CLEANUP, session_host and session_port
             . ./container.sh
+            BUILD_CONTAINER="${CONTAINER}"
+            BUILD_CONTAINER_CLEANUP="${CONTAINER_CLEANUP}"
 
-            trap "${CONTAINER_CLEANUP}" EXIT
+            # Make sure to cleanup build container if something goes
+            # wrong when preparing the test environment
+            if [ x"${BUILD_CONTAINER_CLEANUP}" != x ]; then
+                CONTAINERS_CLEANUP="${BUILD_CONTAINER_CLEANUP}"
+                if [ x"${SSH_AGENT_CLEANUP}" = x ]; then
+                    trap "${CONTAINERS_CLEANUP}" EXIT
+                else
+                    trap "${CONTAINERS_CLEANUP} ; eval \`${SSH_AGENT_CLEANUP}\`" EXIT
+                fi
+            fi
 
             ${CONTAINER} 'echo "Build session is up; ulimit config:"; ulimit -a'
 
