tcwg-buildfarm: Update from tcwg-buildfarm-maxim
This is a major update to switch buildfarm to docker.
Builds are done in docker containers.  Cross-tests are done
on test-armv8-01.tcwglab for gcc-5 (and, temporarily,
aarch64-linux-gnu gcc-6), and inside container on test-armv8-02.tcwglab
for aarch32 linux toolchains.

The updates to tcwg-backport-multijob.yaml and
tcwg-bkk16-trigger-extended.yaml jobs preserve intended semantics of
build matrix configuration.

Change-Id: I9bd024ac988dc883ce80e637fb124fcc3c04c8b4

diff --git a/tcwg-buildfarm.yaml b/tcwg-buildfarm.yaml
--- a/tcwg-buildfarm.yaml
+++ b/tcwg-buildfarm.yaml
@@ -89,9 +89,10 @@
             type: slave
             name: label
             values:
-                - tcwg-x86_64-cam
-                - tcwg-x86_64-2-cam
-                - tcwg-aarch64-build
+                - docker-trusty-amd64-tcwg-build
+                - docker-trusty-i386-tcwg-build
+                - docker-trusty-arm64-tcwg-build
+                - docker-trusty-armhf-tcwg-build
         - axis:
             type: user-defined
             name: target
@@ -104,11 +105,9 @@
                 - aarch64-none-elf
                 - aarch64_be-none-elf
                 - native
-                - schroot-i386-native
-                - schroot-armhf-native
     execution-strategy:
         combination-filter: |
-            (label=="tcwg-x86_64-cam" && target!="schroot-armhf-native" && target!="native" && target!="schroot-i386-native") || (label=="tcwg-x86_64-2-cam" && (target=="native" || target=="schroot-i386-native")) || (label=="tcwg-aarch64-build" && (target=="native" || target=="schroot-armhf-native"))
+            label=="docker-trusty-amd64-tcwg-build" || target=="native"
         sequential: false
     wrappers:
         - timeout:
@@ -124,15 +123,14 @@
         - shell: |
             #!/bin/bash
 
-            set -e
-            set -x
+            set -ex
 
             mkdir -p artifacts/
 
             case "$target--$(uname -m)" in
               native--aarch64) target_kind=native_aarch64 ;;
-              schroot-armhf-native--*) target_kind=native_aarch32 ;;
-              native--x86_64|schroot-i386-native--*) target_kind=native_x86 ;;
+              native--arm*) target_kind=native_aarch32 ;;
+              native--x86_64|native--i686) target_kind=native_x86 ;;
               armeb-linux-gnueabihf--*|*-none-elf--*) target_kind=cross_aux ;;
               *-linux-gnu*--*) target_kind=cross_main ;;
               *) echo "ERROR: Cannot handle target: $target"; exit 1 ;;
@@ -145,121 +143,149 @@
               exit 0
             fi
 
-            case ${target} in
-              schroot-*)
-                schroot_arch=$(echo ${target} | sed -e "s/^schroot-\([^-]*\)-\(.*\)/\1/")
-                target=$(echo ${target} | sed -e "s/^schroot-\([^-]*\)-\(.*\)/\2/")
-                ;;
-              *)
-                case $(uname -m) in
-                  x86_64) schroot_arch="amd64" ;;
-                  aarch64) schroot_arch="arm64" ;;
-                  *) echo "Unexpected architecture $(uname -m)"; exit 1 ;;
+            case "$target_kind-$runtests-$(uname -m)" in
+              "cross_main"-"yes"-*|"cross_main"-"x86_64-host"-"x86_64"|"cross_main"-"x86_64-host"-"i686")
+                case "$target" in
+                  aarch64*) container_arch=arm64 ;;
+                  arm*) container_arch=armhf ;;
+                  *) echo "ERROR: Wrong target $target"; exit 1 ;;
                 esac
+                docker_host="$(echo $DOCKER_HOST | sed -e "s#^tcp://\(.*\):.*#\1#")"
+                ssh_port="$(ssh $docker_host docker port $DOCKER_CONTAINER_ID 22)"
+                ssh_port="$(echo $ssh_port | cut -d: -f 2)"
+                cat > test-container.param << EOF
+            container_name=docker-trusty-$container_arch-tcwg-test
+            upstream_dest=$docker_host:$ssh_port:$WORKSPACE/test-container.data
+            watchdog=upstream
+            EOF
                 ;;
             esac
-            schroot_image="tcwg-build-${schroot_arch}-trusty"
-
-            case $(uname -m) in
-              x86_64) languages="$host_x86_64_languages" ;;
-              *) languages="$host_aarchXX_languages" ;;
-            esac
-
-            case "$runtests-$(uname -m)" in
-              "yes"-*) runtests_opt="--runtests" ;;
-              "x86_64-host"-x86_64) runtests_opt="--runtests" ;;
-              *) runtests_opt="" ;;
-            esac
-
-            if $try_bootstrap; then
-              bootstrap="--bootstrap"
-            else
-              bootstrap=""
+            if echo "$override" | grep -q -e "--extraconfigdir ../config/gcc5" \
+               || true \
+               && [ x"$target" = x"aarch64-linux-gnu" ]; then
+              # Sanitizers in GCC-5 and GCC-6 toolchains for aarch64-linux-gnu
+              # don't support 48-bit VA.  Therefore don't run them on Xenial tester.
+              rm -f test-container.param
             fi
+        - conditional-step:
+            condition-kind: file-exists
+            condition-filename: test-container.param
+            steps:
+                - trigger-builds:
+                    - project: tcwg-test-container-matrix
+                      property-file: test-container.param
+                      block: false
+        - conditional-step:
+            condition-kind: not
+            condition-operand:
+                condition-kind: file-exists
+                condition-filename: artifacts/target-skipped.txt
+            steps:
+              - shell: |
+                  #!/bin/bash
 
-            if [ x"$log_name" != x"" ]; then
-              eval "logname_opt=\"--logname $log_name\""
-            fi
+                  set -ex
 
-            if $rebuild; then
-              norebuild=""
-            else
-              norebuild="--norebuild"
-            fi
+                  if [ -f test-container.param ]; then
+                    runtests_opt="--runtests --testcontainerfile $WORKSPACE/test-container.data"
+                  else
+                    case "$target_kind-$runtests-$(uname -m)" in
+                      *-"yes"-*|*-"x86_64-host"-"x86_64"|*-"x86_64-host"-"i686")
+                        runtests_opt="--runtests"
+                      ;;
+                      *)
+                        runtests_opt=""
+                      ;;
+                    esac
+                  fi
 
-            case $(uname -m) in
-              x86_64) excludecheck="$host_x86_64_excludecheck" ;;
-              *) excludecheck="$host_aarchXX_excludecheck" ;;
-            esac
+                  case $(uname -m) in
+                    x86_64|i686) languages="$host_x86_64_languages" ;;
+                    *) languages="$host_aarchXX_languages" ;;
+                  esac
 
-            excludecheck_opt=""
-            for testsuite in $excludecheck; do
-              excludecheck_opt="$excludecheck_opt --excludecheck $testsuite"
-            done
+                  if $try_bootstrap; then
+                    bootstrap="--bootstrap"
+                  else
+                    bootstrap=""
+                  fi
 
-            # If there were extraconfig options, extract the
-            # corresponding repo
-            if test -n "$extraconfig" ; then
-              git clone http://git.linaro.org/people/christophe.lyon/abe-extraconfigs.git
-            fi
+                  if [ x"$log_name" != x"" ]; then
+                    eval "logname_opt=\"--logname $log_name\""
+                  fi
 
-            extraconfig_opt=""
-            for config in $extraconfig; do
-              case ${extraconfig} in
-                *=*)
-                  tool=${extraconfig%=*}
-                  value=${extraconfig#*=}
-                  ;;
-                *)
-                  echo ERROR: wrong extraconfig: $extraconfig
-                  exit 1
-                  ;;
-              esac
-              extraconfig_opt="${extraconfig_opt} --extraconfig $tool=$PWD/abe-extraconfigs/$value"
-            done
+                  if $rebuild; then
+                    norebuild=""
+                  else
+                    norebuild="--norebuild"
+                  fi
 
-            ulimit -u 5000
+                  case $(uname -m) in
+                    x86_64|i686) excludecheck="$host_x86_64_excludecheck" ;;
+                    *) excludecheck="$host_aarchXX_excludecheck" ;;
+                  esac
 
-            session_id=$(schroot -b -c chroot:$schroot_image --preserve-environment)
-            BUILD_SHELL="schroot -r -c session:$session_id --preserve-environment -- bash"
-            $BUILD_SHELL -c "echo \"Build session is up; ulimit config:\"; ulimit -a"
+                  excludecheck_opt=""
+                  for testsuite in $excludecheck; do
+                    excludecheck_opt="$excludecheck_opt --excludecheck $testsuite"
+                  done
 
-            # Sometimes /dev/pts can't get unmounted on the first try.
-            # Workaround by retrying.
-            trap "{ schroot -f -e -c session:$session_id || { sleep 60 ; schroot -f -e -c session:$session_id; } || true; }" 0
+                  # If there were extraconfig options, extract the
+                  # corresponding repo
+                  if test -n "$extraconfig" ; then
+                    git clone http://git.linaro.org/people/christophe.lyon/abe-extraconfigs.git
+                  fi
 
-            result="0"
-            ${BUILD_SHELL} -x ./jenkins.sh --target ${target} --override "$override" --languages ${languages} $bootstrap $runtests_opt $excludecheck_opt ${extraconfig_opt} --logserver $log_server $logname_opt $norebuild || result=$?
+                  extraconfig_opt=""
+                  for config in $extraconfig; do
+                    case ${extraconfig} in
+                      *=*)
+                        tool=${extraconfig%=*}
+                        value=${extraconfig#*=}
+                        ;;
+                      *)
+                        echo ERROR: wrong extraconfig: $extraconfig
+                        exit 1
+                        ;;
+                    esac
+                    extraconfig_opt="${extraconfig_opt} --extraconfig $tool=$PWD/abe-extraconfigs/$value"
+                  done
 
-            # If we actually built a toolchain, save its manifest.
-            # If the build was a no-op (results already present on log_server),
-            # copy the existing ones.
-            if [ -d _build/builds ]; then
-              manifest="`find _build/builds/ -name destdir -prune -o -name \*manifest.txt -print`"
-            else
-              manifest=""
-            fi
-            if [ x"${manifest}" != x ]; then
-              cp ${manifest} artifacts/
-            else
-              # We need to do the same name expansion as jenkins.sh
-              eval dir="$log_name"
-              scp "$log_server/$dir/*manifest.txt" artifacts/
-            fi
+                  ulimit -u 5000
 
-            echo "Result of jenkins.sh: $result"
-            if $dont_fail; then
-              result="0"
-            fi
-            exit $result
+                  result="0"
+                  /bin/bash -x ./jenkins.sh --target ${target} --override "$override" --languages ${languages} $bootstrap $runtests_opt $excludecheck_opt ${extraconfig_opt} --logserver $log_server $logname_opt $norebuild || result=$?
+
+                  # If we actually built a toolchain, save its manifest.
+                  # If the build was a no-op (results already present on log_server),
+                  # copy the existing ones.
+                  if [ -d _build/builds ]; then
+                    manifest="`find _build/builds/ -name destdir -prune -o -name \*manifest.txt -print`"
+                  else
+                    manifest=""
+                  fi
+                  if [ x"${manifest}" != x ]; then
+                    cp ${manifest} artifacts/
+                  else
+                    # We need to do the same name expansion as jenkins.sh
+                    eval dir="$log_name"
+                    scp "$log_server/$dir/*manifest.txt" artifacts/
+                  fi
+
+                  # Save logs and their directory structure
+                  rsync -a --exclude="/logs/" --include="*/" --include="*.log" --include="*.err" --include="*.out" --include="*.txt" --exclude="*" --prune-empty-dirs ./ ./logs/
+                  if ! tar -I pxz -cf ./artifacts/logs.tar.xz ./logs/; then
+                    # PXZ can [rarely] fail due to high RAM usage, so fallback to normal XZ.
+                    rm -f ./artifacts/logs.tar.xz
+                    tar -cJf ./artifacts/logs.tar.xz ./logs/
+                  fi
+
+                  echo "Result of jenkins.sh: $result"
+                  if $dont_fail; then
+                    result="0"
+                  fi
+                  exit $result
     publishers:
         - archive:
             artifacts: 'artifacts/*'
             latest-only: false
-        - workspace-cleanup:
-            exclude:
-              - "**/*.log"
-              - "**/*.err"
-              - "**/*.out"
-              - "**/*.txt"
-            dirmatch: true
