tcwg-container-christophe: Use tcwg-buildfarm as basis.
For experiments, it seems easier/safer to re-use an existing
job and make only a few changes.

Change-Id: Ic72cf5fe6918fe4648a7777e60a391a4b34cb179

diff --git a/tcwg-container-christophe.yaml b/tcwg-container-christophe.yaml
--- a/tcwg-container-christophe.yaml
+++ b/tcwg-container-christophe.yaml
@@ -60,16 +60,20 @@
             description: 'Do not fail the build'
         - string:
             name: log_server
-            default: dev-01.tcwglab:/home/maxim.kuvyrkov/logs
+            default: dev-01.tcwglab:/home/christophe.lyon/logs
             description: 'Log_Server'
+        - string:
+           name: target_list
+           default: 'aarch64-linux-gnu native'
+           description: 'List of targets to build (aarch64-linux-gnu armv8l-linux-gnueabihf arm-linux-gnueabi arm-linux-gnueabihf armeb-linux-gnueabihf aarch64-none-elf aarch64_be-none-elf arm-eabi native)'
         - string:
             name: abe_branch
             default: refs/remotes/origin/stable
             description: 'ABE revision to test'
         - string:
-           name: target_list
-           default: 'native'
-           description: 'List of targets to use: aarch64-linux-gnu armv8l-linux-gnueabihf arm-linux-gnueabi arm-linux-gnueabihf armeb-linux-gnueabihf aarch64-none-elf aarch64_be-none-elf native'
+            name: scripts_branch
+            default: master
+            description: 'Scripts revision to use'
     disabled: false
     node: tcwg-x86_64-cam
     child-workspace: $target
@@ -89,19 +93,18 @@
             type: slave
             name: label
             values:
-                - tcwg-x86_64-build
+                - tcwg-x86_64-cam
                 - tcwg-x86_32-build
-                - tcwg-apm-build
-                - tcwg-apm_32-build
                 - tcwg-tx1-build
                 - tcwg-tx1_32-build
-                - tcwg-tk1_32-build
         - axis:
             type: dynamic
             name: target
             values:
                 - target_list
     execution-strategy:
+        combination-filter: |
+            label=="tcwg-x86_64-cam" || target=="native"
         sequential: false
     wrappers:
         - timeout:
@@ -121,7 +124,9 @@
 
             mkdir -p artifacts/
 
-            case "$target:$label" in
+            git clone -b $scripts_branch --depth 1 https://git-us.linaro.org/toolchain/jenkins-scripts
+
+            case "$target--$(uname -m)" in
               native--aarch64) target_kind=native_aarch64 ;;
               native--arm*) target_kind=native_aarch32 ;;
               native--x86_64|native--i686) target_kind=native_x86 ;;
@@ -130,46 +135,24 @@
               *) echo "ERROR: Cannot handle target: $target"; exit 1 ;;
             esac
 
-            case "$label" in
-              tcwg-x86_64-build) container_arch="amd64" ;;
-              tcwg-x86_32-build) container_arch="i386" ;;
-              tcwg-apm-build) container_arch="arm64" ;;
-              tcwg-apm_32-build) container_arch="armhf" ;;
-              tcwg-tx1-build) container_arch="arm64" ;;
-              tcwg-tx1_32-build) container_arch="armhf" ;;
-              tcwg-tk1_32-build) container_arch="armhf" ;;
-              docker-*) container_arch="" ;;
-              *) echo "Wrong label: $label"; exit 1 ;;
+            case ${label} in
+                tcwg-x86_64-cam) host_arch=amd64 ;;
+                tcwg-x86_32-build) host_arch=i386 ;;
+                tcwg-tx1-build) host_arch=arm64 ;;
+                tcwg-tx1_32-build) host_arch=armhf ;;
+                *) echo "ERROR: Unsupported slave: $slave"; exit 1 ;;
             esac
+            ./jenkins-scripts/start-container-docker.sh ${host_arch} trusty > container.sh
 
-            case "$label" in
-              tcwg-tk1_32-build) container_type="schroot" ;;
-              tcwg-*-build) container_type="docker" ;;
-              docker-*) container_type="none" ;;
-            esac
-
-            rm -rf container-scripts
-            git clone http://git.linaro.org/people/christophe.lyon/container-scripts.git
-
-            ./container-scripts/start-container-${container_type}.sh ${container_arch} trusty > container.sh
-
-            # Define session_host and session_port, install trap
-            . ./container.sh
-            # At this stage, we don't want to remove the container
-            # when this shell exits, so remove the trap for EXIT we
-            # have just installed
-            trap EXIT
-
-            case "$target:$runtests" in
-              armeb-*:*) ;;
-              *-linux-gnu*:x86_64-host|*-linux-gnu*:yes)
+            case "$target_kind-$runtests-$(uname -m)" in
+              "cross_main"-"yes"-*|"cross_main"-"x86_64-host"-"x86_64"|"cross_main"-"x86_64-host"-"i686")
                 case "$target" in
                   aarch64*) test_container_arch=arm64 ;;
                   arm*) test_container_arch=armhf ;;
                   *) echo "ERROR: Wrong target $target"; exit 1 ;;
                 esac
                 cat > test-container.param << EOF
-            container_name=docker-trusty-$test_container_arch-tcwg-test
+            container_name=docker-trusty-${test_container_arch}-tcwg-test
             upstream_dest=$session_host:$session_port:$WORKSPACE/test-container.data
             watchdog=upstream
             EOF
@@ -182,7 +165,8 @@
               # don't support 48-bit VA.  Therefore don't run them on Xenial tester.
               rm -f test-container.param
             fi
-
+            # Workaround docker service problem on test-armv8-02.tcwglab
+            rm -f test-container.param
         - conditional-step:
             condition-kind: file-exists
             condition-filename: test-container.param
@@ -202,14 +186,16 @@
 
                   set -ex
 
-                  # Define CONTAINER, install trap
+                  # Define session_host and session_port, install trap
                   . ./container.sh
+
+                  ${CONTAINER} 'echo "Build session is up; ulimit config:"; ulimit -a'
 
                   if [ -f test-container.param ]; then
                     runtests_opt="--runtests --testcontainerfile $WORKSPACE/test-container.data"
                   else
-                    case "$runtests-$(uname -m)" in
-                      "yes"-*|"x86_64-host"-"x86_64"|"x86_64-host"-"i686")
+                    case "$target_kind-$runtests-$(uname -m)" in
+                      *-"yes"-*|*-"x86_64-host"-"x86_64"|*-"x86_64-host"-"i686")
                         runtests_opt="--runtests"
                       ;;
                       *)
@@ -270,21 +256,8 @@
                     extraconfig_opt="${extraconfig_opt} --extraconfig $tool=$PWD/abe-extraconfigs/$value"
                   done
 
-                  ${CONTAINER} "echo \"Build session is up; ulimit config:\"; ulimit -a"
-
-                  cat > $WORKSPACE/run.sh << EOF
-                  #!/bin/bash
-                  
-                  cd $WORKSPACE
-                  exec /bin/bash -x ./jenkins.sh --target ${target} --override "$override" --languages ${languages} $bootstrap $runtests_opt $excludecheck_opt ${extraconfig_opt} --logserver $log_server $logname_opt $norebuild
-                  EOF
-                  chmod +x $WORKSPACE/run.sh
                   result="0"
-                  ${CONTAINER} $WORKSPACE/run.sh || result=$?
-
-                  #if [ x"$container_type" = x"docker" ]; then
-                  #  rsync -az -e "ssh -p $session_port" $WORKSPACE/ localhost:$WORKSPACE/
-                  #fi
+                  ${CONTAINER} ${WORKSPACE}/jenkins-scripts/jenkins.sh --abedir ${WORKSPACE} --target ${target} --override "$override" --languages ${languages} $bootstrap $runtests_opt $excludecheck_opt ${extraconfig_opt} --logserver $log_server $logname_opt $norebuild || result=$?
 
                   # If we actually built a toolchain, save its manifest.
                   # If the build was a no-op (results already present on log_server),
