tcwg-make-release: Remove useless canadian cross build.
We need only build 3 toolchains per target: x86_64, i386 and mingw.

So, perform a canadian cross build only when building on
a x86_64 slave.
We used to build twice the mingw toolchain, once on a i386 slave,
once a on x86_64 slave, risking a race condition when copying the
tarball to the fileserver.

Change-Id: Ie7ad5a69270be0b50bf9fdb2782b1217a68d0cf4

diff --git a/tcwg-make-release.yaml b/tcwg-make-release.yaml
--- a/tcwg-make-release.yaml
+++ b/tcwg-make-release.yaml
@@ -142,8 +142,19 @@
             fi
 
             # This job always uses Canadian cross builds and builds 2
-            # toolchains at a time
-            export canadian=true
+            # toolchains at a time when run on a amd64 slave.
+            # When run on a i386 host, no need to duplicate the
+            # Canadian cross build for mingw.
+            case ${label} in
+              docker-*-amd64-tcwg*)
+                export canadian=true ;;
+              docker-*-i386-tcwg*)
+                export canadian=no ;;
+             *)
+                echo "ERROR: unsupported label: ${label}"
+                exit 1
+                ;;
+            esac
             ${shell} ${WORKSPACE}/abe/scripts/MakeRelease.job --target ${target}${tcwg_release:+ --date ${tcwg_release}} --fileserver ${fileserver} --toolchainconfig ${toolchain_config}
             if test $? -gt 0; then
               exit 1
