tcwg_monitoring_disk_users: Add trace flags
Change-Id: I217bfe4f0781ad04cd8a68b860b0d195a356443b

diff --git a/tcwg_monitoring_disk_users.yaml b/tcwg_monitoring_disk_users.yaml
--- a/tcwg_monitoring_disk_users.yaml
+++ b/tcwg_monitoring_disk_users.yaml
@@ -35,6 +35,14 @@
           name: scripts_branch
           default: master
           description: 'Scripts revision to use'
+      - bool:
+          name: verbose
+          default: false
+          description: 'Whether to be verbose'
+      - bool:
+          name: sendmail
+          default: true
+          description: 'Whether send a mail'
 
 - scm:
     name: jenkins
@@ -79,7 +87,15 @@
             #!/bin/bash
             set -ex -o pipefail
             slave_name={slave_name}
+            if $verbose; then
+              export DEBUG=true
+            fi
             ./top-disk-one-slave.sh $slave_name | tee mail-body.txt
+            # We normally send an email upon failure only, so exit
+            #  with 0 if we don't want to send a mail
+            if ! $sendmail; then
+              exit 0
+            fi
     publishers:
         - email-ext:
             recipients: tcwg@linaro.org
