tcwg-test-release.yaml: Work when chained from MakeRelease using parameters file.
Change-Id: I6e378a0e4f3129b77f52f855c9cc5479b33a495c

diff --git a/tcwg-test-release.yaml b/tcwg-test-release.yaml
--- a/tcwg-test-release.yaml
+++ b/tcwg-test-release.yaml
@@ -3,8 +3,8 @@
     project-type: freestyle
     defaults: global
     logrotate:
-        daysToKeep: 10
-        numToKeep: 3
+        daysToKeep: 30
+        numToKeep: 11
     properties:
         - authorization:
             anonymous:
@@ -15,7 +15,7 @@
                 - job-cancel
     parameters:
         - string:
-            name: tarball
+            name: tarball_url
             default: ''
             description: 'The GCC binary tarball to test'
         - string:
@@ -27,7 +27,7 @@
             default: false
             description: 'Whether to enable bash debugging output.'
     disabled: false
-    node: tcwg-x86_64-cam
+    node: tcwg-x86_64-ex40
     retry-count: 3
     concurrent: true
     display-name: 'TCWG Test Release'
@@ -41,22 +41,33 @@
             shallow-clone: true
             wipe-workspace: true
             basedir: abe
-    execution-strategy:
-        sequential: false
     wrappers:
         - timeout:
             timeout: 300
         - timestamps
         - ssh-agent-credentials:
-            # tcwg-buildslave user id
             users:
-                - 'e0958a95-204f-4c14-a66c-5e2be6c5d50a'
+              - 'e0958a95-204f-4c14-a66c-5e2be6c5d50a' # tcwg-buildslave
         - build-name:
-            name: '#${BUILD_NUMBER}${ENV,var="date"}'
-        - matrix-tie-parent:
-            node: master
+            name: '#${BUILD_NUMBER}-${target}'
     builders:
-        - shell: |
+        - shell: |      
             #!/bin/bash
-            bash -x ${WORKSPACE}/abe/scripts/TestRelease.job --tarball ${tarball}
 
+            if test x${debug} = x"true"; then
+              shell="/bin/bash -x"
+              set -x
+            else
+              shell="/bin/bash"
+            fi
+
+            # tarball_url is read from the tcwg.params file, which is
+            # setup by the MakeRelease job.
+            if test x"${tarball_url}" = x; then
+              echo "ERROR: no binary tarball specified!"
+              exit 1
+            fi
+
+            ${shell} ${WORKSPACE}/abe/scripts/TestRelease.job --tarball ${tarball_url}
+
+            exit $?
