tcwg_kernel: Remove stale artifacts before bisect runs
... and cleanup no-longer-necessary debug printouts.

Change-Id: Id4cf50cf896b445803b393c0c3be069b6c96b091

diff --git a/tcwg_kernel.yaml b/tcwg_kernel.yaml
--- a/tcwg_kernel.yaml
+++ b/tcwg_kernel.yaml
@@ -301,11 +301,7 @@
     builders:
         - shell: |
             #!/bin/bash
-            set -e
-            echo "=== Print out environment for debug purposes ==="
-            env | grep "GERRIT\|GIT"
-            echo "=== Environment end  ==="
-            set -x
+            set -ex
             # Delete artifacts now to avoid re-using stale artifacts if
             # below docker-run.sh fails to start up a container.
             rm -rf artifacts/
@@ -438,11 +434,10 @@
     builders:
         - shell: |
             #!/bin/bash
-            set -e
-            echo "=== Print out environment for debug purposes ==="
-            env | grep "GERRIT\|GIT"
-            echo "=== Environment end  ==="
-            set -x
+            set -ex
+            # Delete artifacts now to avoid re-using stale artifacts if
+            # below docker-run.sh fails to start up a container.
+            rm -rf artifacts/
             mkdir -p artifacts/jenkins
             build_name="#$BUILD_NUMBER-$current_project"
             echo "$build_name" > artifacts/jenkins/build-name
