tcwg-update-snapshots_ref: Use correct parameter name
Change-Id: If50ccc238aa549921e6142333cf1995b8e69a659

diff --git a/tcwg-update-snapshots_ref.yaml b/tcwg-update-snapshots_ref.yaml
--- a/tcwg-update-snapshots_ref.yaml
+++ b/tcwg-update-snapshots_ref.yaml
@@ -62,13 +62,14 @@
               opts="-r"
             fi
 
-            case "$slave" in
+            case "$label" in
               tcwg-x86_64-01)
                 machines="$(for i in 2 4 5 6 7 8 9; do echo tcwg-ex40-0$i; done) r1-a7.aus-colo r1-a8.aus-colo"
                 ;;
               tcwg-x86_64-build-01)
                 machines="$(for i in 1 6; do echo build-0$i.tcwglab; done) $(for i in 1 3; do echo apm-0$i.tcwglab; done)"
                 ;;
+              *) echo "ERROR: Unknown host: $label"; exit 1 ;;
             esac
 
             ./scripts/update-snapshots-ref.sh -v $opts $machines
