tcwg_bmk,tcwg_gnu,tcwg_kernel: Bring closer together
Add customizations from tcwg_gnu and tcwg_kernel to tcwg_bmk's stanzas,
which will be later moved to tcwg/round-robin.yaml.inc.

Change-Id: Icb4f3070e1ff28a785ac46bdb230a1ab47681072

diff --git a/tcwg_bmk_ci_gnu.yaml b/tcwg_bmk_ci_gnu.yaml
--- a/tcwg_bmk_ci_gnu.yaml
+++ b/tcwg_bmk_ci_gnu.yaml
@@ -194,7 +194,7 @@
       - string:
           name: ci_config
           default: '{ci_config}'
-          description: "CI configuration ID: gnu-{{toolchain_ver}}-{{target}}-{{bmk}}-{{cflags}}"
+          description: "CI configuration ID"
       - string:
           name: binutils_url
           default: '{binutils_url}'
@@ -251,6 +251,9 @@
             # below docker-run.sh fails to start up a container.
             rm -rf artifacts/
             mkdir -p artifacts/jenkins
+
+            dryruncmd=""
+
             build_name="#$BUILD_NUMBER"
             branch_opt=""
             # 1 to skip jenkins-scripts
@@ -268,6 +271,7 @@
               fi
             done
 
+            $dryruncmd \
             ./jenkins-scripts/docker-run.sh \
               --distro $distro \
               --ssh_info true \
@@ -285,6 +289,12 @@
               $extra_build_params &
             res=0 && wait $! || res=$?
 
+            # If we didn't run the docker command
+            if [ -n "$dryruncmd" ]; then
+              # Mark build unstable aka a skipped config
+              exit 100
+            fi
+
             if [ $res != 0 ]; then
               touch artifacts/failures
             fi
@@ -299,14 +309,21 @@
               build_name="$build_name-bisect"
             fi
             echo "$build_name" > artifacts/jenkins/build-name
-      - trigger-followup-builds:
-          rr_project: '{rr_project}'
-          ci_project_config: '{ci_project_config}'
-      - shell: |
-          #!/bin/bash
-          if [ -f artifacts/failures ]; then
-            exit 1
-          fi
+          unstable-return: 100
+      - conditional-step:
+          # Only run if above succeeded
+          # Meaning we did not skip a bad config
+          # (a failed build is indicated by artifacts/failures)
+          condition-kind: current-status
+          steps:
+            - trigger-followup-builds:
+                rr_project: '{rr_project}'
+                ci_project_config: '{ci_project_config}'
+            - shell: |
+                #!/bin/bash
+                if [ -f artifacts/failures ]; then
+                  exit 1
+                fi
 
 - parameter:
     name: bisect-parameters
@@ -393,9 +410,6 @@
             if [ -f $i ]; then
               echo "ci_project=$ci_project" >> $i
               echo "ci_config=$ci_config" >> $i
-              echo "binutils_url=$binutils_url" >> $i
-              echo "gcc_url=$gcc_url" >> $i
-              echo "glibc_url=$glibc_url" >> $i
               echo "mail_recipients=$mail_recipients" >> $i
               echo "distro=$distro" >> $i
               echo "scripts_branch=$scripts_branch" >> $i
@@ -428,6 +442,7 @@
               ${{FILE,path="artifacts/jenkins/mail-body.txt"}}
             failure: true
             success: true
+            aborted: true
             send-to:
               - recipients
 #END:   tcwg_bmk/tcwg_bmk.yaml.inc
@@ -524,4 +539,4 @@
           ci_project_config: 'tcwg_bmk_{hw}-gnu-{toolchain_ver}-{target}-{bmk}-{cflags}'
     publishers:
         - bisect-publishers
-# checksum: 432178eeac19fd6dffdaf61b6dddd1e5
+# checksum: ee1bc9e9854b6492225c2254248120c0
diff --git a/tcwg_bmk_dev_llvm.yaml b/tcwg_bmk_dev_llvm.yaml
--- a/tcwg_bmk_dev_llvm.yaml
+++ b/tcwg_bmk_dev_llvm.yaml
@@ -140,7 +140,7 @@
       - string:
           name: ci_config
           default: '{ci_config}'
-          description: "CI configuration ID: llvm-{{toolchain_ver}}-{{target}}-{{bmk}}-{{cflags}}"
+          description: "CI configuration ID"
       - string:
           name: binutils_url
           default: '{binutils_url}'
@@ -205,6 +205,9 @@
             # below docker-run.sh fails to start up a container.
             rm -rf artifacts/
             mkdir -p artifacts/jenkins
+
+            dryruncmd=""
+
             build_name="#$BUILD_NUMBER-$ci_project/$ci_config"
             branch_opt=""
             # 1 to skip jenkins-scripts
@@ -218,6 +221,7 @@
               fi
             done
 
+            $dryruncmd \
             ./jenkins-scripts/docker-run.sh \
               --distro $distro \
               --ssh_info true \
@@ -235,6 +239,12 @@
               $extra_build_params &
             res=0 && wait $! || res=$?
 
+            # If we didn't run the docker command
+            if [ -n "$dryruncmd" ]; then
+              # Mark build unstable aka a skipped config
+              exit 100
+            fi
+
             if [ $res != 0 ]; then
               touch artifacts/failures
             fi
@@ -249,14 +259,21 @@
               build_name="$build_name-bisect"
             fi
             echo "$build_name" > artifacts/jenkins/build-name
-      - trigger-followup-builds:
-          rr_project: '{rr_project}'
-          ci_project_config: '{ci_project_config}'
-      - shell: |
-          #!/bin/bash
-          if [ -f artifacts/failures ]; then
-            exit 1
-          fi
+          unstable-return: 100
+      - conditional-step:
+          # Only run if above succeeded
+          # Meaning we did not skip a bad config
+          # (a failed build is indicated by artifacts/failures)
+          condition-kind: current-status
+          steps:
+            - trigger-followup-builds:
+                rr_project: '{rr_project}'
+                ci_project_config: '{ci_project_config}'
+            - shell: |
+                #!/bin/bash
+                if [ -f artifacts/failures ]; then
+                  exit 1
+                fi
 
 - parameter:
     name: bisect-parameters
@@ -342,10 +359,6 @@
             if [ -f $i ]; then
               echo "ci_project=$ci_project" >> $i
               echo "ci_config=$ci_config" >> $i
-              echo "binutils_url=$binutils_url" >> $i
-              echo "gcc_url=$gcc_url" >> $i
-              echo "glibc_url=$glibc_url" >> $i
-              echo "llvm_url=$llvm_url" >> $i
               echo "mail_recipients=$mail_recipients" >> $i
               echo "distro=$distro" >> $i
               echo "scripts_branch=$scripts_branch" >> $i
@@ -378,6 +391,7 @@
               ${{FILE,path="artifacts/jenkins/mail-body.txt"}}
             failure: true
             success: true
+            aborted: true
             send-to:
               - recipients
 #END:   tcwg_bmk/tcwg_bmk.yaml.inc
@@ -471,4 +485,4 @@
             ci_project_config: 'tcwg_bmk_{hw}'
     publishers:
         - bisect-publishers
-# checksum: ca16fc64bd22a25c9f145417b1f846c1
+# checksum: 156780ac5b04a204d97fa9a6577ddb58
