tcwg-llvm-release: run tests after a failed build.
We want to trigger the test job, even if the build fails.

This patch disables the build, so that the job runs quickly
to quickly test the mechanism.

Change-Id: Icad243da7149ff22210e4faf0aa953b0d2168372

diff --git a/tcwg-llvm-release.yaml b/tcwg-llvm-release.yaml
--- a/tcwg-llvm-release.yaml
+++ b/tcwg-llvm-release.yaml
@@ -130,12 +130,18 @@
 
             # Setup job parameters and run (for now, just pretend to run)
             ret=0
-            ${BUILD_CONTAINER} "cd ${WORKSPACE} && bash -x ${WORKSPACE}/tcwg-llvm-release.sh \
+            echo ${BUILD_CONTAINER} "cd ${WORKSPACE} && bash -x ${WORKSPACE}/tcwg-llvm-release.sh \
                 --workspace=${WORKSPACE} \
                 --release=${release} \
                 --candidate=${candidate} \
                 --buildjobs=${buildjobs} \
                 --toolchain=${toolchain}" || ret=$?
+
+            ret=$((BUILD_NUMBER % 2))
+
+            if [ $ret -ne 0 ]; then
+                touch llvm.failed
+            fi
 
             # Chained jobs
             rctag="-rc${candidate}"
@@ -155,7 +161,9 @@
             EOF
             fi
 
-            exit $ret
+            # failure is handled by conditional step on llvm.failed
+            # so that the testsuite job is always triggered
+            exit 0
 
         - conditional-step:
             condition-kind: file-exists
@@ -166,3 +174,8 @@
                       property-file: llvm.params.testsuite
                       current-parameters: true
                       block: true
+        - conditional-step:
+            condition-kind: file-exists
+            condition-filename: llvm.failed
+            steps:
+                - shell: "exit 1"
