tcwg-abe-extended: Do not use schroot inside docker.
Change-Id: I3093a049c5a726f4e11ec49c97850a0ee30d9e77

diff --git a/tcwg-abe-extended.yaml b/tcwg-abe-extended.yaml
--- a/tcwg-abe-extended.yaml
+++ b/tcwg-abe-extended.yaml
@@ -71,16 +71,21 @@
     builders:
         - shell: |
             #!/bin/bash
-            schroot_arch=amd64
-            schroot_image="tcwg-build-${schroot_arch}-trusty"
 
-            session_id=$(schroot -b -c chroot:$schroot_image --preserve-environment)
-            BUILD_SHELL="schroot -r -c session:$session_id --preserve-environment -- bash"
-            $BUILD_SHELL -c "echo \"Build session is up; ulimit config:\"; ulimit -a"
+            if [ "x$label" = "xtcwg-x86_64-cam"; then
+              schroot_arch=amd64
+              schroot_image="tcwg-build-${schroot_arch}-trusty"
 
-            # Sometimes /dev/pts can't get unmounted on the first try.
-            # Workaround by retrying.
-            trap "schroot -f -e -c session:$session_id || { sleep 60 ; schroot -f -e -c session:$session_id; } || true" 0 1 2 3 5 9 13 15
+              session_id=$(schroot -b -c chroot:$schroot_image --preserve-environment)
+              BUILD_SHELL="schroot -r -c session:$session_id --preserve-environment -- bash"
+              $BUILD_SHELL -c "echo \"Build session is up; ulimit config:\"; ulimit -a"
+
+              # Sometimes /dev/pts can't get unmounted on the first try.
+              # Workaround by retrying.
+              trap "schroot -f -e -c session:$session_id || { sleep 60 ; schroot -f -e -c session:$session_id; } || true" 0 1 2 3 5 9 13 15
+            else
+              BUILD_SHELL=bash
+            fi
 
             gccver=gcc=gcc.git~linaro-6.1-2016.08
             case "$testname" in
