tcwg-make-release: Support using tags for releases.
Enable guessing of GCC version from gcc_src parameter when
it is of the form gcc.git~linaro-V.v-YYYY.MM.

Change-Id: I9a8dcdcfe9e6921b6e22f04afae02f71500a3c70

diff --git a/tcwg-make-release.yaml b/tcwg-make-release.yaml
--- a/tcwg-make-release.yaml
+++ b/tcwg-make-release.yaml
@@ -135,8 +135,25 @@
             tcwg_release=${date}
             # If there is no date set, extract release information from the gcc_src
             if test "${date:+set}" != "set"; then
-                tcwg_release="`basename $gcc_src | cut -d '-' -f4-`"
-                tcwg_release=${tcwg_release%".tar.xz"}
+                case "$gcc_src" in
+                *.tar.xz)
+                    tcwg_release="$(basename $gcc_src | cut -d '-' -f4-)"
+                    tcwg_release=${tcwg_release%".tar.xz"}
+                    ;;
+                gcc.git~*)
+                    tcwg_release="$(echo $gcc_src | grep -o -e '-\(20[0-9]\{2\}\.[01][0-9].*\)' )"
+                    tcwg_release=${tcwg_release#-}
+                    ;;
+                *)
+                    echo "ERROR: Could not find tcwg release"
+                    exit 1
+                    ;;
+                esac
+            fi
+
+            if [ x"${tcwg_release}" = x"" ]; then
+                echo "ERROR: Could not find tcwg release"
+                exit 1
             fi
 
             # This job always uses Canadian cross builds and builds 2
@@ -173,7 +190,23 @@
 
                 # Extract the gcc_version information from gcc_src to determine
                 # which directory to copy the tarballs into.
-                gcc_version="`basename $gcc_src | awk -F '-' '{ print $3 }'`"
+                case "$gcc_src" in
+                    *.tar.*) # src tarballs usually named like this
+                        gcc_version=$(basename $gcc_src | awk -F '-' '{ print $3 }')
+                        ;;
+                    *.git~*) # building from git branch or tag
+                        gcc_version=$(basename $gcc_src | awk -F '-' '{ print $2 }')
+                        ;;
+                    *)
+                        echo "ERROR: could not extract version from gcc_src"
+                        exit 1
+                        ;;
+                esac
+                if ! echo "${gcc_version}" | grep -xEq '[0-9]+\.[0-9]+(\.[0-9]+)?'; then
+                    echo "ERROR: gcc version '${gcc_version}' invalid"
+                    exit 1
+                fi
+
                 gcc_major="`echo $gcc_version | awk -F '.' '{ print $1 }'`"
                 gcc_minor="`echo $gcc_version | awk -F '.' '{ print $2 }'`"
                 tcwg_version="${gcc_major}.${gcc_minor}"
