tcwg_kernel: Avoid using stale artifacts when docker-run.sh fails
In https://ci.linaro.org/job/tcwg_kernel-build-llvm-release-aarch64-next-defconfig/39/console we had a strange failure to start a docker container.
I don't understand how container creation could have failed, but it's
expected that failures like this happen from time to time.

What's not OK is that bisection job was then triggered on the basis of
previous artifacts that tcwg_kernel-build.sh:reset_artifacts didn't have
a chance of removing (because the script never started).  The bisection then
notified developers about an attempted bisect via email with very inconsistent
information.

To avoid this we
(1) cleanup artifacts directory in tcwg_kernel.yaml and
(2) make sure that when docker-run.sh fails we create the failure marker
artifacts/failures.

Change-Id: Id9f7f4d216d43b5fe643a2c210e6283bb9148fd8

diff --git a/tcwg_kernel.yaml b/tcwg_kernel.yaml
--- a/tcwg_kernel.yaml
+++ b/tcwg_kernel.yaml
@@ -297,6 +297,9 @@
             env | grep "GERRIT\|GIT"
             echo "=== Environment end  ==="
             set -x
+            # Delete artifacts now to avoid re-using stale artifacts if
+            # below docker-run.sh fails to start up a container.
+            rm -rf artifacts/
             build_name="#$BUILD_NUMBER-$current_project"
             echo "$build_name" > build-name
         - build-name-setter:
@@ -316,7 +319,12 @@
             --linux_config "{linux_config}" \
             --reset_baseline "$reset_baseline" \
             --target "{target}" \
-            --toolchain "{toolchain_name}" || true
+            --toolchain "{toolchain_name}" &
+            res=0 && wait $! || res=$?
+
+            if [ $res != 0 ]; then
+              touch artifacts/failures
+            fi
 
             name="#$BUILD_NUMBER-$current_project"
             if [ -e artifacts/results ]; then
