tcwg-bkk16-trigger-extended-native.yaml: Change ref_build semantic.
ref_build parameter can now be used to point to the last sucessful
build, the previous one, a job number or to build a reference build
(comparison performed) when empty string is passed.

Change-Id: Ia5fa9cc309660a4a6379899c36260c945908031c

diff --git a/tcwg-bkk16-trigger-extended-native.yaml b/tcwg-bkk16-trigger-extended-native.yaml
--- a/tcwg-bkk16-trigger-extended-native.yaml
+++ b/tcwg-bkk16-trigger-extended-native.yaml
@@ -38,10 +38,10 @@
             name: abe_branch
             default: refs/remotes/origin/bkk16
             description: 'ABE revision to test'
-        - bool:
+        - string:
             name: ref_build
-            default: false
-            description: 'Force a reference build (build only, no comparison performed)'
+            default: 'lastSuccess'
+            description: 'Reference build for comparison, e.g., "lastSuccess" or "previous" or job number or empty string to skip comparison'
 
     disabled: false
     node: tcwg-x86_64-dev-01
@@ -76,6 +76,8 @@
 
             set -ex
 
+            shopt -s extglob
+
             gcc_curr_rev=$(git rev-parse HEAD)
             log_prefix="$JOB_NAME-master"
 
@@ -94,11 +96,17 @@
             run_benchmark=false
             EOF
 
-            ref_build_number=$(wget -q --no-check-certificate -O - https://ci.linaro.org/jenkins/job/tcwg-bkk16-trigger-extended-native/lastSuccessfulBuild/buildNumber || true)
+            if [ x"$ref_build" != x ] ; then
+                case "$ref_build" in
+                    lastSuccess)   ref_build_num=$(wget -q --no-check-certificate -O - "${JOB_URL}lastSucessfulBuild/buildNumber") ;;
+                    previous)      ref_build_num=$(wget -q --no-check-certificate -O - "${JOB_URL}lastBuild/buildNumber") ;;
+                    [1-9]*([0-9])) ref_build_num="$ref_build" ;;
+                    *) echo "ERROR: Cannot handle ref_build: $ref_build"; exit 1 ;;
+                esac
 
-            if [ x"$ref_build_number" != x ] && ! $ref_build ; then
-            cat << EOF > compare_results_parameters
-            ref_logs=${log_prefix}-$ref_build_number
+            # Scrambled indentation because of here-doc
+                cat << EOF > compare_results_parameters
+            ref_logs=${log_prefix}-$ref_build_num
             new_logs=${log_prefix}-$BUILD_NUMBER
             log_server=$log_server
             abe_branch=$abe_branch
