tcwg-*: Deprecate i386/i686 containers and hosts.
Change-Id: I58663d3cccab2c03a7682cd62977a39f6ccc3fbd

diff --git a/tcwg-make-release.yaml b/tcwg-make-release.yaml
--- a/tcwg-make-release.yaml
+++ b/tcwg-make-release.yaml
@@ -41,8 +41,8 @@
             description: 'List of targets to use'
         - string:
             name: builder_arch_list
-            default: 'i386 amd64'
-            description: 'List of builder architectures to use (i386,amd64)'
+            default: 'amd64'
+            description: 'List of builder architectures to use (amd64)'
         - string:
             name: abe_branch
             default: tested
@@ -214,7 +214,10 @@
                 canadian=--canadian ;;
               i386)
                 host=i686
-                canadian= ;;
+                canadian=
+                echo "ERROR: i386 hosts no longer unsupported"
+                exit 1
+                ;;
              *)
                 echo "ERROR: unsupported label: ${label}"
                 exit 1
diff --git a/tcwg-test-release.yaml b/tcwg-test-release.yaml
--- a/tcwg-test-release.yaml
+++ b/tcwg-test-release.yaml
@@ -97,7 +97,11 @@
             # Use tarball name to decide if we use an i386 container or an amd64 one
             tarball_file=$(basename ${tarball_url})
             case ${tarball_file} in
-                *-i686*) builder_arch=i386 ;;
+                *-i686*)
+                    builder_arch=i386
+                    echo "ERROR: i386 containers no longer supported for tarball ${tarball_file}"
+                    exit 1
+                    ;;
                 *-x86_64*) builder_arch=amd64 ;;
                 *)
                     echo "ERROR: could not determine container type from tarball ${tarball_file}"
