tcwg_gnu.yaml: Mark build unstable if we skip a known bad config
This way we can tell at a glance what actually
needs fixing. It's not ideal because unstable
usually means test failures. However these jobs
seem to only completely pass or fail.

Also indent the same sections in bmk and
kernel files so that they can still be compared
for refactoring.

Change-Id: Icc7ff0ef504021119ccc318ef6bd4c6e0f9fe39b

diff --git a/tcwg_bmk.yaml b/tcwg_bmk.yaml
--- a/tcwg_bmk.yaml
+++ b/tcwg_bmk.yaml
@@ -353,63 +353,64 @@
           users:
             - 'e0958a95-204f-4c14-a66c-5e2be6c5d50a'
     builders:
-        - shell: |
-            #!/bin/bash
-            set -ex
-            # Delete artifacts now to avoid re-using stale artifacts if
-            # below docker-run.sh fails to start up a container.
-            rm -rf artifacts/
-            mkdir -p artifacts/jenkins
-            build_name="#$BUILD_NUMBER"
-            branch_opt=""
-            i=2
-            for c in {components}; do
-              eval "b=\$$$${{c}}_branch"
-              if [ x"$b" = x"default" ]; then
-                eval "b=\$GIT_COMMIT_$i"
-              fi
-              if [ x"$b" != x"baseline" ]; then
-                build_name="$build_name-$c"
-                branch_opt="$branch_opt ==rr[${{c}}_branch] $b"
-              fi
-              i=$(($i+1))
-            done
+        - shell:
+            command: |
+                #!/bin/bash
+                set -ex
+                # Delete artifacts now to avoid re-using stale artifacts if
+                # below docker-run.sh fails to start up a container.
+                rm -rf artifacts/
+                mkdir -p artifacts/jenkins
+                build_name="#$BUILD_NUMBER"
+                branch_opt=""
+                i=2
+                for c in {components}; do
+                  eval "b=\$$$${{c}}_branch"
+                  if [ x"$b" = x"default" ]; then
+                    eval "b=\$GIT_COMMIT_$i"
+                  fi
+                  if [ x"$b" != x"baseline" ]; then
+                    build_name="$build_name-$c"
+                    branch_opt="$branch_opt ==rr[${{c}}_branch] $b"
+                  fi
+                  i=$(($i+1))
+                done
 
-            ./jenkins-scripts/docker-run.sh \
-            --distro $distro \
-            --ssh_info true \
-            -- \
-            ./jenkins-scripts/tcwg_bmk-build.sh \
-            %% artifacts/jenkins/manifest.sh \
-            --BUILD_URL "$BUILD_URL" \
-            --scripts_branch "$scripts_branch" \
-            --bmk_branch "$bmk_branch" \
-            ==rr[ci_project] tcwg_bmk_{hw} \
-            ==rr[ci_config] {toolchain_name}-{toolchain_ver}-{target}-{bmk}-{cflags} \
-            ==rr[binutils_url] {binutils_url} \
-            ==rr[gcc_url] {gcc_url} \
-            ==rr[glibc_url] {glibc_url} \
-            ==rr[llvm_url] {llvm_url} \
-            $branch_opt \
-            ==rr[mode] "jenkins-full" \
-            ==rr[update_baseline] "$update_baseline" \
-            $extra_build_params &
-            res=0 && wait $! || res=$?
+                ./jenkins-scripts/docker-run.sh \
+                --distro $distro \
+                --ssh_info true \
+                -- \
+                ./jenkins-scripts/tcwg_bmk-build.sh \
+                %% artifacts/jenkins/manifest.sh \
+                --BUILD_URL "$BUILD_URL" \
+                --scripts_branch "$scripts_branch" \
+                --bmk_branch "$bmk_branch" \
+                ==rr[ci_project] tcwg_bmk_{hw} \
+                ==rr[ci_config] {toolchain_name}-{toolchain_ver}-{target}-{bmk}-{cflags} \
+                ==rr[binutils_url] {binutils_url} \
+                ==rr[gcc_url] {gcc_url} \
+                ==rr[glibc_url] {glibc_url} \
+                ==rr[llvm_url] {llvm_url} \
+                $branch_opt \
+                ==rr[mode] "jenkins-full" \
+                ==rr[update_baseline] "$update_baseline" \
+                $extra_build_params &
+                res=0 && wait $! || res=$?
 
-            if [ $res != 0 ]; then
-              touch artifacts/failures
-            fi
+                if [ $res != 0 ]; then
+                  touch artifacts/failures
+                fi
 
-            if [ -e artifacts/results ]; then
-              build_name="$build_name-R$(tail -n1 artifacts/results)"
-            fi
-            if [ x"$update_baseline" != x"update" ]; then
-              build_name="$build_name-$update_baseline"
-            fi
-            if [ -f artifacts/trigger-bisect ]; then
-              build_name="$build_name-bisect"
-            fi
-            echo "$build_name" > artifacts/jenkins/build-name
+                if [ -e artifacts/results ]; then
+                  build_name="$build_name-R$(tail -n1 artifacts/results)"
+                fi
+                if [ x"$update_baseline" != x"update" ]; then
+                  build_name="$build_name-$update_baseline"
+                fi
+                if [ -f artifacts/trigger-bisect ]; then
+                  build_name="$build_name-bisect"
+                fi
+                echo "$build_name" > artifacts/jenkins/build-name
         - trigger-followup-builds:
             hw: '{hw}'
             ci_config: '{toolchain_name}-{toolchain_ver}-{target}-{bmk}-{cflags}'
diff --git a/tcwg_gnu.yaml b/tcwg_gnu.yaml
--- a/tcwg_gnu.yaml
+++ b/tcwg_gnu.yaml
@@ -201,74 +201,77 @@
           users:
             - 'e0958a95-204f-4c14-a66c-5e2be6c5d50a'
     builders:
-        - shell: |
-            #!/bin/bash
-            set -ex
-            # Delete artifacts now to avoid re-using stale artifacts if
-            # below docker-run.sh fails to start up a container.
-            rm -rf artifacts/
-            mkdir -p artifacts/jenkins
+        - shell:
+            command: |
+                #!/bin/bash
+                set -ex
+                # Delete artifacts now to avoid re-using stale artifacts if
+                # below docker-run.sh fails to start up a container.
+                rm -rf artifacts/
+                mkdir -p artifacts/jenkins
 
-            # Don't run these known-bad configurations.
-            case {target}-{type_of_test} in
-              aarch64-bootstrap_profiled|\
-              aarch64-bootstrap_profiled_lto|\
-              aarch64-bootstrap_profiled_lto_lean|\
-              aarch64-check_bootstrap_lto|\
-              arm-bootstrap_profiled|\
-              arm-bootstrap_profiled_lto*|\
-              arm-check_bootstrap_lto)
-                echo "Known bad configuration, not running."
-                touch artifacts/failures
-                exit 1
-                ;;
-            esac
+                # Don't run these known-bad configurations.
+                case {target}-{type_of_test} in
+                  aarch64-bootstrap_profiled|\
+                  aarch64-bootstrap_profiled_lto|\
+                  aarch64-bootstrap_profiled_lto_lean|\
+                  aarch64-check_bootstrap_lto|\
+                  arm-bootstrap_profiled|\
+                  arm-bootstrap_profiled_lto*|\
+                  arm-check_bootstrap_lto)
+                    echo "Known bad configuration, not running."
+                    touch artifacts/failures
+                    # To mark build unstable
+                    exit 100
+                    ;;
+                esac
 
-            build_name="#$BUILD_NUMBER"
-            branch_opt=""
-            i=1
-            for c in {components}; do
-              eval "b=\$$$${{c}}_branch"
-              if [ x"$b" = x"default" ]; then
-                eval "b=\$GIT_COMMIT_$i"
-              fi
-              if [ x"$b" != x"baseline" ]; then
-                build_name="$build_name-$c"
-                branch_opt="$branch_opt ==rr[${{c}}_branch] $b"
-              fi
-              i=$(($i+1))
-            done
+                build_name="#$BUILD_NUMBER"
+                branch_opt=""
+                i=1
+                for c in {components}; do
+                  eval "b=\$$$${{c}}_branch"
+                  if [ x"$b" = x"default" ]; then
+                    eval "b=\$GIT_COMMIT_$i"
+                  fi
+                  if [ x"$b" != x"baseline" ]; then
+                    build_name="$build_name-$c"
+                    branch_opt="$branch_opt ==rr[${{c}}_branch] $b"
+                  fi
+                  i=$(($i+1))
+                done
 
-            ./jenkins-scripts/docker-run.sh \
-            --distro $distro \
-            --arch {docker_arch} \
-            --node $NODE_NAME \
-            -- \
-            ./jenkins-scripts/tcwg_gnu-build.sh \
-            %% artifacts/jenkins/manifest.sh \
-            --BUILD_URL "$BUILD_URL" \
-            ==rr[ci_config] {toolchain_name}-{toolchain_ver}-{target}-{type_of_test} \
-            ==rr[binutils_url] {binutils_url} \
-            ==rr[gcc_url] {gcc_url} \
-            $branch_opt \
-            ==rr[mode] "jenkins-full" \
-            ==rr[update_baseline] "$update_baseline" &
-            res=0 && wait $! || res=$?
+                ./jenkins-scripts/docker-run.sh \
+                --distro $distro \
+                --arch {docker_arch} \
+                --node $NODE_NAME \
+                -- \
+                ./jenkins-scripts/tcwg_gnu-build.sh \
+                %% artifacts/jenkins/manifest.sh \
+                --BUILD_URL "$BUILD_URL" \
+                ==rr[ci_config] {toolchain_name}-{toolchain_ver}-{target}-{type_of_test} \
+                ==rr[binutils_url] {binutils_url} \
+                ==rr[gcc_url] {gcc_url} \
+                $branch_opt \
+                ==rr[mode] "jenkins-full" \
+                ==rr[update_baseline] "$update_baseline" &
+                res=0 && wait $! || res=$?
 
-            if [ $res != 0 ]; then
-              touch artifacts/failures
-            fi
+                if [ $res != 0 ]; then
+                  touch artifacts/failures
+                fi
 
-            if [ -e artifacts/results ]; then
-              build_name="$build_name-R$(tail -n1 artifacts/results)"
-            fi
-            if [ x"$update_baseline" != x"update" ]; then
-              build_name="$build_name-$update_baseline"
-            fi
-            if [ -f artifacts/trigger-bisect ]; then
-              build_name="$build_name-bisect"
-            fi
-            echo "$build_name" > artifacts/jenkins/build-name
+                if [ -e artifacts/results ]; then
+                  build_name="$build_name-R$(tail -n1 artifacts/results)"
+                fi
+                if [ x"$update_baseline" != x"update" ]; then
+                  build_name="$build_name-$update_baseline"
+                fi
+                if [ -f artifacts/trigger-bisect ]; then
+                  build_name="$build_name-bisect"
+                fi
+                echo "$build_name" > artifacts/jenkins/build-name
+            unstable-return: 100
         - trigger-followup-builds:
             ci_config: '{toolchain_name}-{toolchain_ver}-{target}-{type_of_test}'
         - shell: |
