tcwg_bmk, tcwg_gnu, tcwg_kernel: Unify run-build and run-bisect
... builders macro and put them into tcwg/round-robin.yaml.inc.

Change-Id: I76753c7e7f32a139afc2e39cd4f718e07f2446c7

diff --git a/tcwg_kernel-gnu.yaml b/tcwg_kernel-gnu.yaml
--- a/tcwg_kernel-gnu.yaml
+++ b/tcwg_kernel-gnu.yaml
@@ -211,6 +211,84 @@
           description: "What to do with baseline in this build"
       - default-parameters
 
+- builder:
+    name: run-build
+    builders:
+      - shell:
+          command: |
+            #!/bin/bash
+            set -ex
+            # Delete artifacts now to avoid re-using stale artifacts if
+            # below docker-run.sh fails to start up a container.
+            rm -rf artifacts/
+            mkdir -p artifacts/jenkins
+
+            dryruncmd=""
+
+            branch_opt=""
+            # 1 to skip jenkins-scripts
+            i=1
+            for c in {components}; do
+              eval "u=\$$$${{c}}_url"
+              eval "b=\$$$${{c}}_branch"
+              if [ x"$b" != x"baseline" ]; then
+                build_name="$build_name-$c"
+                branch_opt="$branch_opt ==rr[${{c}}_url] $u ==rr[${{c}}_branch] $b"
+              fi
+            done
+
+            $dryruncmd \
+            ./jenkins-scripts/docker-run.sh \
+              --distro $distro \
+              -- \
+              ./jenkins-scripts/tcwg_kernel-build.sh \
+              %% artifacts/jenkins/manifest.sh \
+              --BUILD_URL "$BUILD_URL" \
+              --scripts_branch "$scripts_branch" \
+              ==rr[ci_project] $ci_project \
+              ==rr[ci_config] $ci_config \
+              $branch_opt \
+              ==rr[mode] "jenkins-full" \
+              ==rr[update_baseline] "$update_baseline" \
+              $extra_build_params &
+            res=0 && wait $! || res=$?
+
+            # If we didn't run the docker command
+            if [ -n "$dryruncmd" ]; then
+              # Mark build unstable aka a skipped config
+              exit 100
+            fi
+
+            if [ $res != 0 ]; then
+              touch artifacts/failures
+            fi
+
+            if [ -e artifacts/results ]; then
+              build_name="$build_name-R$(tail -n1 artifacts/results)"
+            fi
+            if [ x"$update_baseline" != x"update" ]; then
+              build_name="$build_name-$update_baseline"
+            fi
+            if [ -f artifacts/trigger-bisect ]; then
+              build_name="$build_name-bisect"
+            fi
+            echo "$build_name" > artifacts/jenkins/build-name
+          unstable-return: 100
+      - conditional-step:
+          # Only run if above succeeded
+          # Meaning we did not skip a bad config
+          # (a failed build is indicated by artifacts/failures)
+          condition-kind: current-status
+          steps:
+            - trigger-followup-builds:
+                rr_project: '{rr_project}'
+                ci_project_config: '{ci_project_config}'
+            - shell: |
+                #!/bin/bash
+                if [ -f artifacts/failures ]; then
+                  exit 1
+                fi
+
 - parameter:
     name: bisect-parameters
     parameters:
@@ -238,6 +316,46 @@
           name: jenkins-scripts/replay_log
           description: "Replay part of bisect using provided bisect log"
       - default-parameters
+
+- builder:
+    name: run-bisect
+    builders:
+      - shell:
+          command: |
+            #!/bin/bash
+            set -ex
+            # Delete artifacts now to avoid re-using stale artifacts if
+            # below docker-run.sh fails to start up a container.
+            rm -rf artifacts/
+            mkdir -p artifacts/jenkins
+            echo "$build_name" > artifacts/jenkins/build-name
+            # artifacts/jenkins/mail-*.txt will be overwritten in successful builds.
+            echo "maxim.kuvyrkov@linaro.org" > artifacts/jenkins/mail-recipients.txt
+            echo "Build $BUILD_URL failed" > artifacts/jenkins/mail-body.txt
+
+            ./jenkins-scripts/docker-run.sh \
+              --distro $distro \
+              -- \
+              ./jenkins-scripts/round-robin-bisect.sh \
+              %% artifacts/manifests/bisect.sh \
+              --BUILD_URL "$BUILD_URL" \
+              --current_project "$current_project" \
+              --bad_url "$bad_url" \
+              --bad_branch "$bad_branch" \
+              --replay_log "$(pwd)/jenkins-scripts/replay_log" \
+              --build_script "./jenkins-scripts/tcwg_bmk-build.sh" \
+              -- \
+              --scripts_branch "$scripts_branch" \
+              ==rr[ci_project] $ci_project \
+              ==rr[ci_config] $ci_config \
+              $extra_build_params
+
+            if [ x"$mail_recipients" != x"default" ]; then
+              echo "$mail_recipients" > artifacts/jenkins/mail-recipients.txt
+            fi
+      - trigger-followup-builds:
+          rr_project: '{rr_project}'
+          ci_project_config: '{ci_project_config}'
 #END:   tcwg/round-robin.yaml.inc
 
 - job-template:
@@ -286,66 +404,10 @@
           users:
             - 'e0958a95-204f-4c14-a66c-5e2be6c5d50a'
     builders:
-      - shell:
-          command: |
-            #!/bin/bash
-            set -ex
-            # Delete artifacts now to avoid re-using stale artifacts if
-            # below docker-run.sh fails to start up a container.
-            rm -rf artifacts/
-            mkdir -p artifacts/jenkins
-            build_name="#$BUILD_NUMBER"
-            branch_opt=""
-            # 1 to skip jenkins-scripts
-            i=1
-            for c in {components}; do
-              eval "u=\$$$${{c}}_url"
-              eval "b=\$$$${{c}}_branch"
-              if [ x"$b" = x"default" ]; then
-                eval "b=\$GIT_COMMIT_$i"
-              fi
-              if [ x"$b" != x"baseline" ]; then
-                build_name="$build_name-$c"
-                branch_opt="$branch_opt ==rr[${{c}}_url] $u ==rr[${{c}}_branch] $b"
-              fi
-              i=$(($i+1))
-            done
-
-            ./jenkins-scripts/docker-run.sh \
-            --distro $distro \
-            -- \
-            ./jenkins-scripts/tcwg_kernel-build.sh \
-            %% artifacts/jenkins/manifest.sh \
-            --BUILD_URL "$BUILD_URL" \
-            ==rr[ci_project] $ci_project \
-            ==rr[ci_config] $ci_config \
-            $branch_opt \
-            ==rr[mode] "jenkins-full" \
-            ==rr[update_baseline] "$update_baseline" &
-            res=0 && wait $! || res=$?
-
-            if [ $res != 0 ]; then
-              touch artifacts/failures
-            fi
-
-            if [ -e artifacts/results ]; then
-              build_name="$build_name-R$(tail -n1 artifacts/results)"
-            fi
-            if [ x"$update_baseline" != x"update" ]; then
-              build_name="$build_name-$update_baseline"
-            fi
-            if [ -f artifacts/trigger-bisect ]; then
-              build_name="$build_name-bisect"
-            fi
-            echo "$build_name" > artifacts/jenkins/build-name
-      - trigger-followup-builds:
+      - run-build:
+          components: '{components}'
           rr_project: 'tcwg_kernel-gnu'
           ci_project_config: '{toolchain_name}-{toolchain_ver}-{target}-{linux}-{linux_config}'
-      - shell: |
-          #!/bin/bash
-          if [ -f artifacts/failures ]; then
-            exit 1
-          fi
     publishers:
         - archive:
             artifacts: 'artifacts/**'
@@ -390,40 +452,9 @@
               credential-id: TCWG_JIRA_PASSWORD
               variable: TCWG_JIRA_PASSWORD
     builders:
-        - shell: |
-            #!/bin/bash
-            set -ex
-            # Delete artifacts now to avoid re-using stale artifacts if
-            # below docker-run.sh fails to start up a container.
-            rm -rf artifacts/
-            mkdir -p artifacts/jenkins
-            build_name="#$BUILD_NUMBER-$current_project"
-            echo "$build_name" > artifacts/jenkins/build-name
-            # artifacts/jenkins/mail-*.txt will be overwritten in successful builds.
-            echo "maxim.kuvyrkov@linaro.org" > artifacts/jenkins/mail-recipients.txt
-            echo "Build $BUILD_URL failed" > artifacts/jenkins/mail-body.txt
-
-            ./jenkins-scripts/docker-run.sh \
-            --distro $distro \
-            -- \
-            ./jenkins-scripts/round-robin-bisect.sh \
-            %% artifacts/manifests/bisect.sh \
-            --BUILD_URL "$BUILD_URL" \
-            --current_project "$current_project" \
-            --bad_url "$bad_url" \
-            --bad_branch "$bad_branch" \
-            --build_script "./jenkins-scripts/tcwg_kernel-build.sh" \
-            --JIRA_PASSWORD "$TCWG_JIRA_PASSWORD" \
-            -- \
-            ==rr[ci_project] $ci_project \
-            ==rr[ci_config] $ci_config
-
-            if [ x"$mail_recipients" != x"default" ]; then
-              echo "$mail_recipients" > artifacts/jenkins/mail-recipients.txt
-            fi
-        - trigger-followup-builds:
-            rr_project: 'tcwg_kernel-gnu'
-            ci_project_config: '{toolchain_name}-{toolchain_ver}-{target}-{linux}-{linux_config}'
+      - run-bisect:
+          rr_project: 'tcwg_kernel-gnu'
+          ci_project_config: '{toolchain_name}-{toolchain_ver}-{target}-{linux}-{linux_config}'
     publishers:
         - archive:
             artifacts: 'artifacts/**'
@@ -437,4 +468,4 @@
             success: true
             send-to:
               - recipients
-# checksum: aff326b541bdb031fe1103e8368c2094
+# checksum: f908cb721ba98fa411b69e792d9d188d
