tcwg-buildfarm: Stop containers for failed builds
... rather then keep them running.  Running containers consume resources,
and, for tcwg-*-test nodes, can skew board usage statistic, which
print_node_with_least_containers relies on.

Change-Id: I79bee15e59897ec49ce33c1fbcd00a071d010360

diff --git a/tcwg-buildfarm.yaml b/tcwg-buildfarm.yaml
--- a/tcwg-buildfarm.yaml
+++ b/tcwg-buildfarm.yaml
@@ -236,9 +236,10 @@
 
             ${build_CONTAINER_RSH} "cd ${WORKSPACE} && bash -x ${WORKSPACE}/jenkins-scripts/jenkins.sh --workspace ${WORKSPACE} --abedir ${WORKSPACE} $target_opt --override \"$override\" --languages ${languages} $bootstrap $runtests_opt $excludecheck_opt ${extraconfig_opt} --logserver $log_server $logname_opt $norebuild" || result=$?
 
-            # If the build failed, we want to keep the containers to investigate the problem, so remove the cleanup trap handler.
+            # If the build failed, stop the containers, which will
+            # leave them as-is for ~10 days.
             if [ $result -ne 0 ]; then
-                trap - EXIT
+                trap "build_container_stop; test_container_stop" EXIT
             fi
 
             # If we actually built a toolchain, save its manifest.
